import { SkillProficiency } from '../types';
import { Ability } from './Ability';

export enum Skill {
  Acrobatics = 'Acrobatics',
  AnimalHandling = 'Animal Handling',
  Arcana = 'Arcana',
  Athletics = 'Athletics',
  Deception = 'Deception',
  History = 'History',
  Insight = 'Insight',
  Intimidation = 'Intimidation',
  Investigation = 'Investigation',
  Medicine = 'Medicine',
  Nature = 'Nature',
  Perception = 'Perception',
  Performance = 'Performance',
  Persuasion = 'Persuasion',
  Religion = 'Religion',
  SleightOfHand = 'Sleight of Hand',
  Stealth = 'Stealth',
  Survival = 'Survival',
}

export const SkillProficiencies: SkillProficiency[] = [
  {
    skill: Skill.Acrobatics,
    proficiencyLevel: 0,
    baseAbility: Ability.Dexterity,
  },
  {
    skill: Skill.AnimalHandling,
    proficiencyLevel: 0,
    baseAbility: Ability.Wisdom,
  },
  {
    skill: Skill.Arcana,
    proficiencyLevel: 0,
    baseAbility: Ability.Intelligence,
  },
  {
    skill: Skill.Athletics,
    proficiencyLevel: 0,
    baseAbility: Ability.Strength,
  },
  {
    skill: Skill.Deception,
    proficiencyLevel: 0,
    baseAbility: Ability.Charisma,
  },
  {
    skill: Skill.History,
    proficiencyLevel: 0,
    baseAbility: Ability.Intelligence,
  },
  { skill: Skill.Insight, proficiencyLevel: 0, baseAbility: Ability.Wisdom },
  {
    skill: Skill.Intimidation,
    proficiencyLevel: 0,
    baseAbility: Ability.Charisma,
  },
  {
    skill: Skill.Investigation,
    proficiencyLevel: 0,
    baseAbility: Ability.Intelligence,
  },
  { skill: Skill.Medicine, proficiencyLevel: 0, baseAbility: Ability.Wisdom },
  {
    skill: Skill.Nature,
    proficiencyLevel: 0,
    baseAbility: Ability.Intelligence,
  },
  {
    skill: Skill.Perception,
    proficiencyLevel: 0,
    baseAbility: Ability.Wisdom,
  },
  {
    skill: Skill.Performance,
    proficiencyLevel: 0,
    baseAbility: Ability.Charisma,
  },
  {
    skill: Skill.Persuasion,
    proficiencyLevel: 0,
    baseAbility: Ability.Charisma,
  },
  {
    skill: Skill.Religion,
    proficiencyLevel: 0,
    baseAbility: Ability.Intelligence,
  },
  {
    skill: Skill.SleightOfHand,
    proficiencyLevel: 0,
    baseAbility: Ability.Dexterity,
  },
  {
    skill: Skill.Stealth,
    proficiencyLevel: 0,
    baseAbility: Ability.Dexterity,
  },
  { skill: Skill.Survival, proficiencyLevel: 0, baseAbility: Ability.Wisdom },
];

export enum WeaponProficiencies {
  'Light Armor',
  'Medium Armor',
  'Heavy Armor',
  'Shields',
  'Simple Weapons',
  'Martial Weapons',
  'Unarmed Strike',
  'Daggers',
  'Shortswords',
  'Longswords',
  'Greatswords',
  'Morningstars',
  'Pikes',
  'Polearms',
  'Quarterstaffs',
  'Hand Crossbows',
  'Handaxes',
  'Rapiers',
  'Scimitars',
  'Tridents',
  'War Picks',
  'Warhammers',
  'Whips',
  'Blowguns',
  'Crossbows',
  'Longbows',
  'Shortbows',
  'Slings',
  'Darts',
  'Javelins',
  'Spears',
  'Battleaxes',
  'Flails',
  'Glaives',
  'Greataxes',
  'Halberds',
  'Lances',
  'Mauls',
}
