import { Abilities } from './Abilities';

interface SkillProficiency {
  skill: string;
  proficiencyLevel: 0 | 1 | 2 | 3;
  baseAbility: Abilities;
}

export const SkillProficiencies: SkillProficiency[] = [
  {
    skill: 'Acrobatics',
    proficiencyLevel: 0,
    baseAbility: Abilities.Dexterity,
  },
  {
    skill: 'Animal Handling',
    proficiencyLevel: 0,
    baseAbility: Abilities.Wisdom,
  },
  {
    skill: 'Arcana',
    proficiencyLevel: 0,
    baseAbility: Abilities.Intelligence,
  },
  {
    skill: 'Athletics',
    proficiencyLevel: 0,
    baseAbility: Abilities.Strength,
  },
  {
    skill: 'Deception',
    proficiencyLevel: 0,
    baseAbility: Abilities.Charisma,
  },
  {
    skill: 'History',
    proficiencyLevel: 0,
    baseAbility: Abilities.Intelligence,
  },
  { skill: 'Insight', proficiencyLevel: 0, baseAbility: Abilities.Wisdom },
  {
    skill: 'Intimidation',
    proficiencyLevel: 0,
    baseAbility: Abilities.Charisma,
  },
  {
    skill: 'Investigation',
    proficiencyLevel: 0,
    baseAbility: Abilities.Intelligence,
  },
  { skill: 'Medicine', proficiencyLevel: 0, baseAbility: Abilities.Wisdom },
  {
    skill: 'Nature',
    proficiencyLevel: 0,
    baseAbility: Abilities.Intelligence,
  },
  {
    skill: 'Perception',
    proficiencyLevel: 0,
    baseAbility: Abilities.Wisdom,
  },
  {
    skill: 'Performance',
    proficiencyLevel: 0,
    baseAbility: Abilities.Charisma,
  },
  {
    skill: 'Persuasion',
    proficiencyLevel: 0,
    baseAbility: Abilities.Charisma,
  },
  {
    skill: 'Religion',
    proficiencyLevel: 0,
    baseAbility: Abilities.Intelligence,
  },
  {
    skill: 'Sleight of Hand',
    proficiencyLevel: 0,
    baseAbility: Abilities.Dexterity,
  },
  {
    skill: 'Stealth',
    proficiencyLevel: 0,
    baseAbility: Abilities.Dexterity,
  },
  { skill: 'Survival', proficiencyLevel: 0, baseAbility: Abilities.Wisdom },
];

const WeaponProficiencies = [
  'Light Armor',
  'Medium Armor',
  'Heavy Armor',
  'Shields',
  'Simple Weapons',
  'Martial Weapons',
  'Unarmed Strike',
  'Daggers',
  'Short Swords',
  'Long Swords',
  'Great Swords',
  'Rapiers',
  'Scimitars',
  'Hand Crossbows',
  'Crossbows',
  'Blowguns',
  'Longbows',
  'Shortbows',
  'Slings',
  'Battleaxes',
  'Flails',
  'Glaives',
  'Greataxes',
  'Greatswords',
  'Halberds',
  'Lances',
  'Mauls',
  'Morningstars',
  'Pikes',
  'Polearms',
  'Quarterstaffs',
  'Scimitars',
  'Shortswords',
  'Spears',
  'Tridents',
  'War Picks',
  'Warhammers',
  'Whips',
  'Hand Crossbows',
  'Crossbows',
  'Blowguns',
  'Longbows',
  'Shortbows',
  'Slings',
  'Light Hammers',
  'Handaxes',
  'Rapiers',
  'Scimitars',
  'Shortswords',
  'Tridents',
  'War Picks',
  'Warhammers',
  'Whips',
  'Blowguns',
  'Crossbows',
  'Longbows',
  'Shortbows',
  'Slings',
  'Darts',
  'Javelins',
  'Spears',
  'Battleaxes',
  'Flails',
  'Glaives',
  'Greataxes',
  'Greatswords',
  'Halberds',
  'Lances',
  'Mauls',
];
